### ISSUE TITLE
Ошибка при выполнении --start

### ISSUE THREAD

**Issue by ikonovalenko** [FastVPSEestiOu/vzrepair#3]
При запуске vzrepair с параметром --start получаю ошибку:
```
# vzrepair --ctid 1001 --password rand --start --silent --json 
Use of uninitialized value in concatenation (.) or string at /usr/local/sbin/vzrepair line 256.
```
Скрипт выполняется и выдаёт результат в виде json, но из-за этой ошибки перед json при попытке обработать json средствами PHP ничего не выйдет.

При --status или --stop такой ошибки нет.

**Comment by mrqwer88** [comment]
В данном случае предупреждение выдается, так-как у контейнера не задан hostname (и нет проверки на его наличие при добавлении "repair." к нему в скрипте).

Предупреждение идет в stderr, в stdout идет валидный json.
В любом случае случае не стоит отдавать вывод stderr парсеру json-а, так-как в нем наличие валидного json не предполагается.

**Comment by mrqwer88** [comment]
https://github.com/FastVPSEestiOu/vzrepair/commit/b35867f9b59448ba82b0585bd729f5cad293c868

Добавил проверку - в этом месте предупреждение больше не будет выдаваться, при отсутствии заданного hostname у контейнера.
Но вызов vzrepair из PHP все равно лучше изменить так, что бы только stdout попадал в парсер json.
